services:
    finance.pportfolio_voter:
        class: FinanceBundle\Security\PortfolioVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false