<?php

namespace FinanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PortfolioItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioItemRepository extends EntityRepository
{
}
